version: 'v3'

tasks:
  install:
    desc: "Install dependencies"
    cmds:
      - "go mod tidy"
      
  run:
    desc: "Run the Go project"
    cmds:
      - "go run ./main.go"
  
  build:
    desc: "Build the Go project"
    cmds:
      - "go build -o bin/main ./cmd/main/main.go"

  test:
    desc: "Run tests"
    cmds:
      - "go test ./..."

  clean:
    desc: "Clean the build artifacts"
    cmds:
      - "rm -rf bin"

  lint:
    desc: "Run linter"
    cmds:
      - "golangci-lint run"