version: 'v3'

tasks:
  install:
    desc: "Install dependencies"
    cmds:
      - "go mod tidy"

  run:
    desc: "Run the Go project"
    cmds:
      - "go run ./main.go"
  
  build:
    desc: "Build the Go project"
    cmds:
      - "go build -o bin/main ./main.go"

  test:
    desc: "Run tests"
    cmds:
      - "go test ./..."
  
  test:coverage:
    desc: "Run tests with coverage"
    cmds:
      - "go test --cover ./..."

  test:coverage:html:
    desc: "Run tests with coverage and generate HTML report"
    cmds:
      - "go test --coverprofile=coverage.out ./..."
      - "go tool cover -html=coverage.out"

  clean:
    desc: "Clean the build artifacts"
    cmds:
      - "rm -rf bin"

  lint:
    desc: "Run linter"
    cmds:
      - "golangci-lint run"